name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-alpine:
    name: Alpine ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x86]

    steps:
    - uses: actions/checkout@v3

    - name: Install latest stable Alpine Linux
      uses: jirutka/setup-alpine@master
      with:
        arch: ${{ matrix.Platform }}
        branch: 'latest-stable'
        packages: build-base cmake bison flex nasm xz sed sdl2-dev zlib-dev libogg-dev libvorbis-dev
        
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"
        
    - name: Run CMake
      shell: alpine.sh {0}
      run: |
        cd ${{github.workspace}}/Sources 
        find . -name "CMakeLists.txt" -exec sed -i 's/-march=native/-mtune=generic/g' {} +
        cat CMakeLists.txt | grep mtune
        cmake -B ${{github.workspace}}/Sources/build-x86 -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 -DUSE_I386_NASM_ASM=TRUE -DTFE=TRUE

    - name: Run Build
      shell: alpine.sh {0}
      run: |
          cd ${{github.workspace}}/Sources/build-x86    
          make ecc
          make -j$(nproc || echo 4)
          cp -vfr Debug/*.so ../../x32/SamTFE/Mods/SSA/Bin
          cd ${{github.workspace}}
          tar -cJpvf SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-lnx-x86-bin.tar.xz x32
          
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-lnx-x86-bin.tar.xz
        path: SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-lnx-x86-bin.tar.xz          

  build-ubuntu-x64:
    name: Ubuntu ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y libsdl2-dev libogg-dev libvorbis-dev &&
          sudo apt-get install -qq -y bison flex sed zlib1g-dev      

    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"
        
    - name: Run CMake
      run: |
          cd ${{github.workspace}}/Sources
          find . -name "CMakeLists.txt" -exec sed -i 's/-march=native/-mtune=generic/g' {} +
          cat CMakeLists.txt | grep mtune
          cmake -B ${{github.workspace}}/Sources/build-x64 -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DTFE=TRUE
          
    - name: Run Build
      run: |
          cd ${{github.workspace}}/Sources/build-x64    
          make ecc
          make -j$(nproc || echo 4)
          cp -vfr Debug/*.so ../../x64/SamTFE/Mods/SSA/Bin
          cd ${{github.workspace}}
          XZ_DEFAULTS="-T 10" tar --use-compress-program=xz -cpvf SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-lnx-amd64-bin.tar.xz x64
          
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-lnx-amd64-bin.tar.xz
        path: SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-lnx-amd64-bin.tar.xz 

  build-windows-x86:
    name: Windows ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [Win32]
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-version: '14.0'
        
    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"
               
    - name: MS Build
      working-directory: Sources
      run: | 
         msbuild /m /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" SSA.sln 
         cd ${{github.workspace}}
         7z a -mx=9 SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-win32-bin.7z x32
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-win32-bin.7z
        path: SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-win32-bin.7z 
        
  build-windows-x64:
    name: Windows ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]
    steps:
    - uses: actions/checkout@v3

    - uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-version: '14.0'

    - name: Get current date
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
         format: "YYYYMMDD"

    - name: Show current date
      run: |
        echo "${{ steps.date.outputs.time }}"
        
    - name: MS Build
      working-directory: Sources
      run: | 
         msbuild /m /p:Configuration="${{ matrix.Configuration }}" /p:Platform="${{ matrix.Platform }}" SSA.sln 
         cd ${{github.workspace}}
         7z a -mx=9 SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-win64-bin.7z x64
      
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-win64-bin.7z
        path: SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-win64-bin.7z        

  build-freebsd-x64:
    name: FreeBSD ${{ matrix.Configuration }} ${{ matrix.Platform }}
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release]
        Platform: [x64]    
    steps:
      - uses: actions/checkout@v3

      - name: Get current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYYMMDD"

      - name: Show current date
        run: |
          echo "${{ steps.date.outputs.time }}"
          
      - name: Build on FreeBSD
        uses: cross-platform-actions/action@v0.10.0
        with:
          operating_system: freebsd
          architecture: x86-64
          version: '13.1'
          shell: bash
          run: |
            uname -a
            sudo pkg install -y bison flex sdl2 libogg libvorbis zlib-ng cmake
            cd ${{github.workspace}}/Sources
            awk '{sub("-march=native","-mtune=generic")}1' CMakeLists.txt > CmakeTemp.txt && mv CmakeTemp.txt CMakeLists.txt
            cat CMakeLists.txt | grep mtune
            cmake -B ${{github.workspace}}/Sources/build-x64 -DCMAKE_BUILD_TYPE=${{ matrix.Configuration }} -DTFE=TRUE
            cd ${{github.workspace}}/Sources/build-x64
            make ecc
            make -j$(sysctl -n hw.ncpu || echo 4)
            cp -vfr Debug/*.so ../../x64/SamTFE/Mods/SSA/Bin
            cd ${{github.workspace}}
            XZ_DEFAULTS="-T 10" tar --use-compress-program=xz -cpvf SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-bsd-amd64-bin.tar.xz x64
                      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-bsd-amd64-bin.tar.xz
          path: SeriousSamAlphaRemake-${{ steps.date.outputs.time }}-bsd-amd64-bin.tar.xz      
